---
version: '3'

services:
  zookeeper:
    extends:
      file: ./kafka_cluster/docker-compose.yml
      service: zookeeper
  # -----------------------      
  broker:
    extends:
      file: ./kafka_cluster/docker-compose.yml
      service: broker
    depends_on:
      - zookeeper
  # -----------------------     
  create_topic:
    extends:
      file: ./create_topic/docker-compose.yml
      service: create_topic
    depends_on:
      - broker
    container_name: create_topic_test
    environment:
      - TOPIC=test
  # -----------------------     
  device_1:
    extends:
      file: ./iot_data_gen/docker-compose.yml
      service: iot_data_gen
    depends_on:
      - create_topic
    container_name: device_1
    command:
      [
        "--device_struct",
        '[{"name":"sensor_1","properties":{"obs_frequency":"1"}},{"name":"sensor_2","properties":{"obs_frequency":"1"}}]',
        "--topic",
        "test",
        "--bootstrap_server",
        "host.docker.internal:9092"
      ]
