---
version: '3'
services:
  create_topic:
    depends_on:
      - broker
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: create_topic:latest
    container_name: default
    environment:
      - TOPIC=default
      - BOOTSTRAP_SERVER=localhost:9092
