---
version: '3'
services:
  consumer_pyspark_console:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: consumer_pyspark_console:latest
    container_name: consumer_pyspark_console
    environment:
      - TOPIC=default
      - BOOTSTRAP_SERVER=localhost:9092
